### ISSUE TITLE
Swagger UI module is not working

### ISSUE THREAD

**Issue by Chinna-SearsHomeServices** [gregwhitaker/catnap#2]
hi, 
catnap utility works great. I could see following issue while using swagger api. I am using swagger ui module in Spring-boot REST service
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.5.0</version>
		</dependency>

While try to access the following url, i am getting the error as like below
URL --> http://localhost:8080/swagger-ui.html
Error --> [o.s.web.servlet.PageNotFound] - No mapping found for HTTP request with URI [/swagger-ui.html] in DispatcherServlet with name 'dispatcherServlet'

If I comment @EnableCatnap annotation, my swagger works again. have you had any issue while using swagger ui module?

**Comment by gregwhitaker** [comment]
The issue is caused by the fact that the `@EnableCatnap` annotation uses Spring's `DelegatingWebMvcConfiguration` class under the covers.  This is breaking Spring Boot's view resolver.  I'll have to look into a way to get around this issue.  Perhaps I can create a separate module for Spring Boot that uses `WebMvcConfigurerAdapter` and preserves Spring Boot's static content view resolvers.

**Comment by gregwhitaker** [comment]
I have created a separate module for springboot.  If you import `com.github.gregwhitaker:catnap-springboot:2.1.0` you should be able to use the swagger ui without issues.

**Comment by Chinna-SearsHomeServices** [comment]
Verified and works great. Thanks for the quick enhancement
